version: '3'

services:
  miageland-db:
    image: postgres:latest
    container_name: miageland-db
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=miageland
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    networks:
      - mynetwork
  miageland-db-test:
    image: postgres:latest
    container_name: miageland-db-test
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=miageland-test
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    networks:
      - mynetwork

networks:
  mynetwork: