version: '3'

services:
  miageland-db:
    image: postgres:latest
    container_name: miageland-db
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=miageland
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"